### ISSUE TITLE
Where did Full-Window go?

### ISSUE THREAD

**Issue by karasuhebi** [CoenraadS/News-Ticker#4]
Hey sorry to post this here but I don't know of any other way to get a hold of you. What happened to Full-Window did you delete the repo? If so, may I ask why?

**Comment by CoenraadS** [comment]
Hey, I set the repo to private because there are better alternatives available, and I got frustrated that games that previously worked with my program stopped working in later releases. However I set it to public again, but for now am not working on it and suggest you look here: http://pcgamingwiki.com/wiki/Glossary:Borderless_fullscreen_windowed for alternatives.
